### ISSUE TITLE
Gusto: Key Badges

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#1]
The Gusto space requires key badges for the outer door and the inner door

We need to badges for:
- Students from BE4, FE1, and FE2
- Remaining Instructors: Question of who

@stevekinney - Which instructors still need badges? (Nate, Bree, etc?)
@jcasimir - What is the status of the request to Gusto for badges?

**Comment by jcasimir** [comment]
@allisonreusinger is now working on gathering and delivering the information to Gusto. I'm hoping that we can get a batch from them today to alleviate some of the door-opening burden.

**Comment by rrgayhart** [comment]
👍 Thanks Jeff - removed you from the issue and assigned to @allisonreusinger

**Comment by rrgayhart** [comment]
Update: Jorge sent out a drive folder to all students to get the info to be sent to Gusto this afternoon

**Comment by stevekinney** [comment]
On the topic of instructor badges: I suspect that they'll want to give instructors photo badges just like the students as opposed to the temporary ones we have now. Also: I'm sure that they don't love that there is a mismatch between names assigned to the cards and the people who actually are using them.

It looks like we'd officially need cards for the following staff:
- Steve
- Meeka
- Louisa
- Nate
- Jhun
- Brenna
- Bree
- Taylor

**Comment by novohispano** [comment]
@steve We have everyone but Taylor. :( I'll add him but it might be too late.

**Comment by novohispano** [comment]
@steve Taylor is added to the spreadsheet. We'll see if they pick it up this time.

**Comment by rrgayhart** [comment]
@novohispano @stevekinney - The badges seem to be in the students hands. Did anyone get missed or can we close this issue?
