### ISSUE TITLE
TVs and HDMI splitters to Gusto

### ISSUE THREAD

**Issue by stevekinney** [turingschool/ops-issues#10]
We're going to do our first FEE-2/BEE-4 joint lesson on Tuesday and it would be super if we could get the second television from Champa over to Gusto. In addition, I think the TVs work way better than the projectors for teaching.

Let's do:
- 2 televisions in the bigger classrooms (4 altogether)
- 1 in the smaller classroom

Action items:
- Do we know where the second big television from Champa is, @jcasimir?
- Can we order three more of the very big televisions, @RachelMartinez?

**Comment by RachelMartinez** [comment]
I have reached out to Jody who works with us on studio space to see if we can get a refund, in which case we would try and move out completely this weekend (I believe),  @jcasimir and I had a conversation about the tv's and getting them moved/ordered, not sure where he usually does this from? Jeff, if you can do this or give me the info that would be great.  I will loop in @novohispano because I am not sure how much bandwidth I have right now to coordinate the logistics of a total move from Champa so would need some participation from other ops members.

**Comment by jcasimir** [comment]
It looks like we could get the big ones from Best Buy cheaper than Amazon
and there are three in stock in Westminster:

http://www.bestbuy.com/site/sharp-65-class-64-5-diag--led-2160p-smart-4k-ultra-hd-tv-gray/4970100.p?id=bb4970100&skuId=4970100

I bet our Nick/Sonny combo would be up for doing it today or tomorrow
afternoon if we purchased them ahead of time. I'll ask Andrea to work on it
and update you all.

**Comment by Jeff-Duke** [comment]
Here are the carts we ordered for Champa they allow the TV's to be mounted higher and make them more visible from the back of the room: 

https://www.amazon.com/Elitech-Mobile-Stand-Middle-Shelf/dp/B00Z1CR1HW/ref=sr_1_5?s=furniture&rps=1&ie=UTF8&qid=1469731802&sr=1-5&keywords=TV+cart&refinements=p_85%3A2470955011%2Cp_n_feature_keywords_two_browse-bin%3A7018703011%2Cp_n_material_browse%3A316589011

**Comment by rrgayhart** [comment]
@Jeff-Duke @RachelMartinez @stevekinney - How much of these materials are:
1. Already at Gusto?
2. Ordered and being shipped?
3. Not yet ordered?

**Comment by stevekinney** [comment]
3 new TVs arrived on Thursday and were set up by Nick and Pete. I haven't been to Champa since the initial move, but I suspect the HDMI splitter setup for two of the TVs is there. There is also a TV that was left behind when we were going to consider using Champa as a classroom.

I will leave it to @novohispano's discretion on what should move and what should stay and what should get ordered but I would say we need to get a least one more splitter and make sure we have five TVs total at Gusto.

**Comment by rrgayhart** [comment]
So @novohispano 

Have:
- 3 TVs 
- 1 HDMI splitter (was not working when I used it)

Need:
- 2 more TVs
- 2 HDMI splitters (to be safe)

Suspect:
There is one TV at Gusto

**Comment by novohispano** [comment]
@rrgayhart What specs do you need? We have ordered 65 in, 48 in and 40 in TVs in the past. Do you need carts or mounts as well?

**Comment by rrgayhart** [comment]
I assume (and I'm only assuming) - that the last TV order was the right size and that we need a cart/mount for any new TVs - this is what Jeff linked for the mounts that they used: https://www.amazon.com/Elitech-Mobile-Stand-Middle-Shelf/dp/B00Z1CR1HW/ref=sr_1_5?s=furniture&rps=1&ie=UTF8&qid=1469731802&sr=1-5&keywords=TV+cart&refinements=p_85%3A2470955011%2Cp_n_feature_keywords_two_browse-bin%3A7018703011%2Cp_n_material_browse%3A316589011

If we move the TV that Steve thinks is at Champa, I don't know if it has a mount or not

**Comment by Jeff-Duke** [comment]
afaik we only ever had 1 HDMI splitter at champa for the 2 tv's that we had initially.  I believe that is the one that nick moved over and it was working properly when we set up the  new TV's.  It would be good to get 2 more of the carts I linked above for the TV's that are going in the north(ish) room that 1608 FEE has been using.  They will also need an HDMI splitter for that setup.

**Comment by rrgayhart** [comment]
#26 - should help with finalizing an exact order for this.

**Comment by stevekinney** [comment]
The 65-inch TVs are essential for rooms that aren't wide and short like at Blake Street.

**Comment by jcasimir** [comment]
If I'm understanding our current status correctly:
- We have sufficient 65" TVs at this point at Gusto for instruction
- We want/need a splitter setup to power 3-4 TVs for larger group sessions

Is that right?
