### ISSUE TITLE
Gusto: Cubbies Set Up

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#11]
This will probably be wrapped up in moving everything from Champa this weekend.

We need to:
- Get cubbies from Champa location
- Augment Champa cubbies with enough for FE1 (not sure if we have a bunch or need to order more)
- Find a place for said cubbies in the Gusto location

**Comment by mjvalade** [comment]
Lots of cubbies (not sure if all/enough) will fit in the cabinets below the main counter in Gusto so we might not need the cubbie containers, or at least not as many since we are limited on space.

**Comment by RachelMartinez** [comment]
@rrgayhart Do some of the students at Gusto currently have Cubbies at Champa, and are there still personal belongings in those cubbies? If FE2 has not gotten cubbies yet then I can order them.  If FE1 has stuff in their cubbies, I would encourage them to go get them and take them to Gusto.  If the cubbies are empty they are much easier to transport.

**Comment by novohispano** [comment]
@rrgayhart Do you know whether FEE students have cubbies at Champa?

**Comment by rrgayhart** [comment]
@novohispano - FEE Mod 2 does have some. Mod 1 does not.

**Comment by rrgayhart** [comment]
#26 - will help with confirming this
