### ISSUE TITLE
Gusto: Standing Tables

### ISSUE THREAD

**Issue by Jeff-Duke** [turingschool/ops-issues#12]
We had ordered legs and stools for Champa to set up a row of standing desks.  Can we get those moved to Gusto and set up the back rows as standing?

(Also we don't have the rights to add labels to issues)

**Comment by rrgayhart** [comment]
@jcasimir @novohispano - Where are the legs and stools that were ordered for Champa? Still at Champa? 

If so, can we task someone to get those fellers moved over? We can task me and my truck, just don't want to make that trip if they aren't there. The final move is still pending, so it would be great to not wait until then for a quick run.

**Comment by Jeff-Duke** [comment]
there should be 1 table that has already been converted at champa, 2 sets of legs still in boxes as well.  I'm not sure if Joanne got the additional stools ordered prior to going on maternity leave.
