### ISSUE TITLE
Gusto: white boards

### ISSUE THREAD

**Issue by ckaminer** [turingschool/ops-issues#13]
White boards at gusto would be nice if we can find space

**Comment by rrgayhart** [comment]
There are boards in the main classrooms but the conference room has neither a board nor a place we could fit a free standing board.

Are we allowed to mount anything on the walls here @novohispano?

**Comment by jcasimir** [comment]
We at least need to get permission to mount anything. Freestanding would be better but are a pain to have taking up floor space.

**Comment by rrgayhart** [comment]
In the conference room, there isn't room for a white board at the front of the room and mounting one on the side would be difficult (as there really isn't much room to stand and write on one over there).

How would we feel about instead getting some of these and a stand to put in the front corner? 

https://www.amazon.com/Post--Self-Stick-Easel-Inches-30-Sheet/dp/B00006IA9F/ref=sr_1_1?ie=UTF8&qid=1472411871&sr=8-1&keywords=large+writing+tablet+paper

**Comment by novohispano** [comment]
@rrgayhart I'm fine with whatever works for your. Can we get confirmation that this is what you need? (cc @ckaminer)

**Comment by rrgayhart** [comment]
Cool - I'll order once I get an answer to #25 and confirmation that this'll work on Monday

**Comment by jcasimir** [comment]
I added them to the cart but haven't placed the order yet. There are several pads like this at Blake, too. Closing for now.
