### ISSUE TITLE
Gusto: Pairing Stations

### ISSUE THREAD

**Issue by Jeff-Duke** [turingschool/ops-issues#14]
Currently the smallest mod occupies pretty much all of the pairing stations.  With 3 mods all having paired projects it'd be nice to have some additional stations available.

**Comment by stevekinney** [comment]
I suspect that we can probably fit at least three more stations in Pairing Alley and then Even more along the back walls of the middle classroom. I'll pull @novohispano into this to see what our options are.

**Comment by jcasimir** [comment]
Let's figure out the Champa close-down first which will dictate how much if any furniture/equipment could be repurposed.

**Comment by stevekinney** [comment]
Just a quick note—both FEE cohorts in SAB notes are complaining that BEE Module 4 is "taking up all of the pairing stations." I _don't_ think this is a problem with Module 4 per se, but I do think that we need to figure out the "more pairing stations" issue sooner than later.

**Comment by allisonreusinger** [comment]
I also encouraged all three cohorts to come to Blake when they have extended work time to use pairing stations there too, since it's not far from Gusto. Just because we might max out on space at Gusto soon for pairing stations

**Comment by saylerb** [comment]
Are there extra unused monitors at blake st that we can take over to Gusto? We may not need full pairing station setups, but a couple extra screens would help a lot.

**Comment by stevekinney** [comment]
Yea. That sounds good. Even for evaluations, we only really need monitors. Could you own this @saylerb? If the monitors don't work we can coordinate buying now ones.

**Comment by Jeff-Duke** [comment]
There are unused new larger monitors in boxes at champa and carts to go with them.  We could get those together and get some keyboards to make portable pairing stations.

**Comment by rrgayhart** [comment]
@Jeff-Duke @saylerb - Looks like some heros set up the TVs.

What do we need for monitors and keyboards? If you can give us a rough count we can make a new issue and 
1. Move over anything we need that is already at Champs or Blake
   1. Order the rest of the things that we need

**Comment by Jeff-Duke** [comment]
I believe there are 4 larger (30"+) monitors still at champa that could be moved over, I believe there are carts for most of them still at champa as well.  We would need at least 4 keyboards and 4 mice to go along with those.

**Comment by rrgayhart** [comment]
@Jeff-Duke - You are a gentleman and a scholar - I'll try to get an inventory #26 from Champa so we can make an order
