### ISSUE TITLE
Gusto: Trash

### ISSUE THREAD

**Issue by saylerb** [turingschool/ops-issues#15]

**Comment by saylerb** [comment]
Not enough trash bin space! We need larger containers, or they need to be emptied more frequently.

**Comment by rrgayhart** [comment]
@saylerb - We ordered two new mega trash cans in a materials order from Amazon a few days ago -> #6 . I'll keep this open until we actually get the delivery but Rachel already handled it 💃

**Comment by RachelMartinez** [comment]
The kitchen sized trash cans are in the blakement as of now.  They will make their way over to Gusto at some point on Monday.  If anybody has a burning desire, you are welcome to come to Blake and pick them up!  The mega trash can is still in transit.

**Comment by rrgayhart** [comment]
Nate brought the trashcans and bags. Nate is a hero.
