### ISSUE TITLE
Gusto: Water Bottles Out

### ISSUE THREAD

**Issue by kansasraptor** [turingschool/ops-issues#17]
We need it.

**Comment by rrgayhart** [comment]
@kansasraptor - Can you be more specific about which location? (Blake or Gusto). In the water coolers? In bottles? In general, because of Global Warming? ;)

**Comment by kansasraptor** [comment]
We are out of the culligan (sp?) bottles.

**Comment by rrgayhart** [comment]
#8 <- we rerouted deliveries to Gusto in this issue - @RachelMartinez heads up, it looks like they haven't delivered the water yet!

**Comment by stevekinney** [comment]
@neight-allen brought up that we should probably up the quantity of bottles delivered as we've gone from 20 people to 50 people.

**Comment by RachelMartinez** [comment]
Water is coming on its usual delivery day, which I believe was Thursday.  I can up the quantity.

**Comment by RachelMartinez** [comment]
The water order has been doubled.  The delivery can only be every two weeks, however Water will be delivered at Gusto tomorrow during the day at some point.  No exact ETA as guy is fitting us into his route tomorrow and is not sure when he will make it over.
