### ISSUE TITLE
Gusto: Dishwasher

### ISSUE THREAD

**Issue by neight-allen** [turingschool/ops-issues#20]
I don't know how much it costs, or whether it's worth the setup, but we do have counter space for a counter dishwasher, like the ones we have at Blake. I think it would be nice to have, and may be similar cost to all the paper plates, plastic cups and plastic silverware we'd have to buy.

Also, maybe we need dishes.

**Comment by novohispano** [comment]
@RachelMartinez what do you think about this one?

**Comment by RachelMartinez** [comment]
I could look into whether we are allowed for one, and whether the plumbing is set up for something like that.

**Comment by jcasimir** [comment]
We've looked at this and, at this time, are not going to install a dishwasher at Gusto. It's about the lease, plumbing, and liability problems, not the cost.

**Comment by neight-allen** [comment]
Cool. Thanks!
