### ISSUE TITLE
HR/Paperwork: Name Change

### ISSUE THREAD

**Issue by kansasraptor** [turingschool/ops-issues#21]
I'm not sure who to ask about this, but is there a way I can change my name? I am listed as Laura Sellers in all frontend.turing references and Laura Allen in some other places.  Can I change my name to Laura Allen across the board?

**Comment by rrgayhart** [comment]
@RachelMartinez @mikedao - Do ya'll know what we need to do for this? Update roster/turing profiles?

**Comment by mikedao** [comment]
It's been changed in roster, and I went and changed it in apply/enroll. Last places I can think of are perhaps the attendance sheets for FEE? @stevekinney ?

**Comment by novohispano** [comment]
@mikedao I don't think the FEE program has attendance sheets for this module. We can add another issue to that.
