### ISSUE TITLE
FEE: Attendance Sheets

### ISSUE THREAD

**Issue by novohispano** [turingschool/ops-issues#22]
We need to create the attendance sheets for the FEE.

**Comment by rrgayhart** [comment]
@mikedao / @stevekinney  - Do we have these already?
@novohispano - If we don't, who should we assign the task to?

**Comment by mikedao** [comment]
Joanne usually makes them. I made the BEE ones for this inning. If you would like FEE ones made, I can do that rather quickly.

**Comment by mikedao** [comment]
I just went ahead and created the spreadsheets, they are in the FEE Attendance folder on Google Drive.

**Comment by rrgayhart** [comment]
@mikedao == hero.

**Comment by novohispano** [comment]
@mikedao Thanks much! 👍
