### ISSUE TITLE
Gusto: Chairs

### ISSUE THREAD

**Issue by Jeff-Duke** [turingschool/ops-issues#23]
Can we get the chairs from Champa moved to Gusto and give the current Gusto chairs back to Gusto/University of the Rockies?  The current chairs aren't meant for multi-hour use for the next several modules and result in poor ergonomics.

**Comment by rrgayhart** [comment]
@jcasimir - My understanding is that part of the deal with renting the space from Gusto was the fact that we had to keep the things in the space that it came with - is that accurate?

**Comment by RachelMartinez** [comment]
@rrgayhart Yes, we would need written permission, which would probably require an actual plan and a place to keep the current chairs.  No guarantees that it is allowed.

**Comment by jcasimir** [comment]
@Jeff-Duke I'm curious about the research/backstory -- you're talking about the rolling chairs in the classrooms? Or the 4-legged chairs that are mostly in the lobby/pairing areas? Or all of them?

**Comment by Jeff-Duke** [comment]
@jcasimir yeah the rolling chairs that came with the space.  They have no adjustability and therefore no way to position yourself accordingly with the tables.  I've personally noticed more back/neck/shoulder strain using the stations here than when we were at Champa.  I just figured since the Ikea chairs are sitting at Champa we could get them moved over.  Didn't realize that we are required to keep all of this furniture in place.  Maybe when we get the standing tables added per #28 it'll be better.

**Comment by RachelMartinez** [comment]
I am closing this issue as it has been discussed and the furniture that is in the temporary space is staying in the temporary space and we will not be adding any additional temporary furniture.
