### ISSUE TITLE
Gusto: Shipping Rules and Address

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#25]
Are we allowed to ship things from Amazon directly to Gusto?

If yes, what is the mailing address we should use?

**Comment by RachelMartinez** [comment]
I believe you could ship to here:  
1201 16TH Street
Denver, Colorado 80202 
Suite 110
If you could just coordinate with me for the office supplies stuff before you make an order that would be great.  We currently have about 300 dry erase markers and 20 erasers.

**Comment by rrgayhart** [comment]
👍 Will check any orders with you before I make them!
