### ISSUE TITLE
Gusto: Cubbies, TVs and Pairing Stations

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#28]
Consolidating and closing #14, #12, #11 and #10 
## Gusto needs/has requested:
- More screens and keyboards (approx. 5 stations, 10 keyboards, 10 mice)
- Cubbies for FEE1(17) and FEE2(21) - staff (~8)- 46 total cubbies 
- Standing tables and stools
- 1 HDMI splitter
- 1 to 2 large tvs for instruction? (@stevekinney - please confirm if this is still accurate based on what you have now)
- Easel pads and an Easel to replace a whiteboard in the conference room
## Champa currently has (need to be moved):
- 5  red stools (one still in box)
- 1 assembled standing desk
- 1 regular desk and a box of unassembled leg extenders
- 2 Eight unit cubby boxes (2 cubbies tall, 4 wide) - approx 8 cubbies left unclaimed - random junk in cubbies.
- 1 Large TV (65 inches?)
- 2 TV stands (assembled no TVs - silver and black)
- 2 TVs (40” TCLs) on assembled stands (black, new stands) with HDMI cables
- 2 TVs (40” TCLs) in boxes
- 2 1/2 Easel Pads
- 1 monitor (with HDMI cable)
- 3 wired keyboards
- 2 wired mice
## Things Still Required (may be at Blake, or need to be ordered)
- 7 wired keyboards
- 8 wired mice
- 1 Easel for the Easel Pads to live on
- Approx 30 cubbies - and either cubby holders for them or use of the drawers beneath the coffee maker
- 1 HDMI splitter
- 1 additional TV stand (unless the large TV at Champa is not needed for Gusto - or we don't use one of the 40" tvs)

**Comment by RachelMartinez** [comment]
cubbies,easel and pads are ordered and being shipped to Gusto.

**Comment by stevekinney** [comment]
I am happy to order more splitters and HDMI cables if they haven't been ordered yet. But, I just thought I would check first.

**Comment by RachelMartinez** [comment]
If Jeff or Jorge didn't order it then please do! I dont trust myself to get the specs right on that stuff

**Comment by Jeff-Duke** [comment]
the 2 black/silver TV stands at champa are missing the brackets needed to attach a TV.  We had to order new carts.  If we'd like to have the 2 65" TV's in the 1608FE classroom on the taller carts we'll need to order those.

**Comment by stevekinney** [comment]
Do you have a link to the item on Amazon per chance?

**Comment by Jeff-Duke** [comment]
@stevekinney 

https://www.amazon.com/Elitech-Mobile-Stand-Middle-Shelf/dp/B00Z1CR1HW/ref=sr_1_5?s=furniture&rps=1&ie=UTF8&qid=1469731802&sr=1-5&keywords=TV+cart&refinements=p_85%3A2470955011%2Cp_n_feature_keywords_two_browse-bin%3A7018703011%2Cp_n_material_browse%3A316589011

**Comment by ccgamble** [comment]
What is the status of getting some standing desks/stools to the classrooms at Gusto?

**Comment by RachelMartinez** [comment]
We have boxes of unopened mounting brackets for tv's at Blake.  they have been sitting in boxes for awhile, so please do not order more.

**Comment by RachelMartinez** [comment]
Splitters and other items ordered for Gusto.  Cubbies are there and we have mounting brackets.  Standing desks are not an option at this time and will not be ordered for this space. I am closing this issue.
