### ISSUE TITLE
Blake: 🐛 and fruit flies

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#29]
Created issue to track ongoing efforts at Blake to combat the fruit fly problem.

**Comment by RachelMartinez** [comment]
We have 2 pest control companies and they have set traps.  It takes some time.  It is also a building issue in the laundry room that the maintenance needs to take care of, which I will email again right now.

**Comment by jcasimir** [comment]
I ordered a second attractor light and more of the sticky cards which should all arrive today.

**Comment by RachelMartinez** [comment]
I think these have mostly improved, however as long as we are basement dwellers there may be some out and about here and there.  I am closing this issue as we have done what we can do and will keep the current pest control and fruit fly traps in place.
