### ISSUE TITLE
Gusto: Hours Clarification

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#3]
Students are not sure how long they are allowed to be in the building at night - if they can access over the weekends. It would be good to get clarity on the exact hours they are allowed to be here and get the info out to students.

**Comment by jcasimir** [comment]
What we agreed to with Gusto:
- Instructors 7am - 7pm
- Student badges 8AM - 5PM
- Student access outside 8AM to 5PM with instructor "supervision"

We can be very generous with the definition of supervision. To play it safe would be to elect one person who's responsible for kicking everyone out and closing up when they're done.

**Comment by rrgayhart** [comment]
@jcasimir Awesome - does that include weekend hours? I assume not...

**Comment by rrgayhart** [comment]
I'll post this in all student channels and then close this issue

Hello friends. I know you all have questions on Gusto hours!

Gusto is planning to give all students key code badges. They require names and emails for all students - so Allison is getting that worked out. Should get the first wave of badges this week.

For accessing the building, our agreement with Gusto is:

Instructors 7am - 7pm
Student badges 8AM - 5PM
Student access outside 8AM to 5PM with instructor "supervision"

We can be flexible with what 'supervision' means - but generally plan to be out when the instructors leave or by 5pm.

You are welcome 24 hours a day at Blake Street. The code for the inner doors there is 36521. DM me if you don't know the code to be in the building. ALWAYS close the inner doors if you are there or leaving after hours.
