### ISSUE TITLE
Inner Front Door Handle Broken

### ISSUE THREAD

**Issue by mikedao** [turingschool/ops-issues#31]
The inner front door handle is broken. This is the door you open after inputting the code to access the building. It is broken in the fact that the part of the handle you grasp has been snapped off. The door still appears to lock, and can be open by turning the part that still remains.

**Comment by RachelMartinez** [comment]
I have reached out to the building management and they are aware of the situation.

**Comment by mikedao** [comment]
The door handle has been fixed.
