### ISSUE TITLE
Gusto: Coffee Machine

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#5]
Did the coffee machine come from Champa to Gusto during the move?

If yes: Needs to be set up so we don't keep paying for coffee

If no: Someone needs to go rescue it and set it up

**Comment by RachelMartinez** [comment]
I will be rescuing the coffee machine in the morning.  My morning starts when the nanny comes to take over baby related stuff, so it will be there by 930-10ish.
