### ISSUE TITLE
Gusto: Amazon Order for Materials

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/ops-issues#6]
Rachel Martinez is currently ordering:
- 2 large trashcans
- Electronic and cleaning wipes
- Forks/Spoons/Knives/Cups/Napkins/Etc

Comment below if there are extra items that should be ordered

**Comment by RachelMartinez** [comment]
Order is placed!

**Comment by rrgayhart** [comment]
I'm going to re-open this until the materials actually make it to Gershtow (which is how I now like to say Gusto)

**Comment by RachelMartinez** [comment]
I am on my way now.  How do I get in with above said supplies?

**Comment by rrgayhart** [comment]
All major materials from this order except for trash cans (tracked in #15) seem to be at Gusto - so closing this.
