### ISSUE TITLE
Blake: Water Cooler broken near Staff tables

### ISSUE THREAD

**Issue by case-eee** [turingschool/ops-issues#7]
The water cooler is broken near the staff tables. It makes weird beeping noises when plugged in.

**Comment by RachelMartinez** [comment]
This is now unplugged and drying out.  When the catch bucket gets to full it overflows and floods some sensor.  It will dry out and should work again by tomorrow.  Allison is adding "empty the water cooler bucket" to the daily cleaning list.  This will hopefully keep the problem from happening in the future.

**Comment by case-eee** [comment]
thanks @RachelMartinez 🎉

**Comment by jcasimir** [comment]
Fixed.
