### ISSUE TITLE
Champa: Closing down location

### ISSUE THREAD

**Issue by novohispano** [turingschool/ops-issues#9]
@RachelMartinez is going to see whether we can get a partial reimbursement and close the location this week.

**Comment by RachelMartinez** [comment]
Update: I spoke with Jody on Friday and she is going to see about my request for a refund to vacate early.  I should hear back from her early this week.

**Comment by jcasimir** [comment]
We're waiting on a brief agreement for the 3rd floor space at GBank. I expect that we'll at least get access to the space this Wednesday or Thursday to begin relocating furniture and closing Champa.

**Comment by rrgayhart** [comment]
https://docs.google.com/a/casimircreative.com/document/d/1U3wLGhkFskcW90nqW0opzgoOXgADKKxYDKYJHoYrDNQ/edit?usp=sharing

Current (as of today) inventory of what is at Champa. Would strongly recommend a moving company.

Have some large sticky notes of what belongs to Champa and what belongs to us - but should have a member of our staff directing the move.

Also - Champa needs a day of heads up if we plan to park behind the building (where the elevator lift is located). Access on the weekends is not guarenteed.

**Comment by RachelMartinez** [comment]
The move will be done tomorrow evening.
